# Configurações de build para projetos Vite
[build]
  command = "npm run build"
  publish = "dist"

# Regra para servir diretamente os arquivos de exercícios (pasta public/exercises)
[[redirects]]
  from = "/exercises/*"
  to = "/exercises/:splat"
  status = 200
  force = true

# Regra geral para SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200